export type SourceOfTruthStatus = "ready" | "shadow" | "planned" | "env-gated" | "guarded" | "locked" | "bridge-planned" | "audit-required" | "read-shadow" | "reconciliation" | "requires-approval" | "controlled" | "blocked";
export type ProductReadiness = { websiteWebApp: number; taskProjectCore: number; backendApi: number; databasePrismaSeed: number; authRbac: number; iotOps: number; mobileApp: number; };
export type SourceDomainId = "tasks" | "projects" | "stock" | "pontaj" | "audit" | "adminControls" | "users" | "documents" | "crm" | "offers" | "procurement" | "iotOps" | "reports" | "mobile";
export type SotMetric = { id: string; label: string; value: string; trend: string; status: SourceOfTruthStatus; evidence: string; };
export type SotDomain = { id: SourceDomainId; label: string; summary: string; adapter: string; entity: string; readiness: number; mode: SourceOfTruthStatus; owner: string; endpoint: string; writeMode: string; sourceSystem: string; targetSystem: string; goLiveCriteria: string[]; blockers: string[]; };
export type SotAdapter = { id: string; label: string; domain: SourceDomainId; kind: string; mode: SourceOfTruthStatus; readiness: number; endpoint: string; healthEndpoint: string; requiredEnv: string[]; capabilities: string[]; evidence: string; };
export type SotContract = { id: string; entity: string; domain: SourceDomainId; fields: string[]; purpose: string; readiness: number; version: string; auditRequired: boolean; rbacRequired: boolean; rollbackRequired: boolean; persistenceTarget: string; };
export type SotSyncLane = { id: string; label: string; domain: SourceDomainId; direction: string; cadence: string; mode: SourceOfTruthStatus; readiness: number; guardrail: string; audit: string; rollback: string; };
export type SotReconciliation = { id: string; label: string; domain: SourceDomainId; rule: string; readiness: number; severity: string; action: string; evidence: string; };
export type SotFlow = { id: string; label: string; summary: string; source: SourceDomainId; target: SourceDomainId; status: SourceOfTruthStatus; readiness: number; contract: string; adapter: string; audit: string; rollback: string; };
export type SotRunbook = { id: string; title: string; owner: string; steps: string[]; evidence: string; };
export type SotCommand = { id: string; title: string; domain: SourceDomainId; state: SourceOfTruthStatus; requiresApproval: boolean; command: string; evidence: string; };
export type SotRisk = { id: string; title: string; domain: SourceDomainId; severity: string; status: string; mitigation: string; owner: string; };
export type Release = { ok: boolean; version: string; name: string; generatedAt: string; productionWrites: string; summary: string; readiness: ProductReadiness; metrics: SotMetric[]; domains: SotDomain[]; adapters: SotAdapter[]; contracts: SotContract[]; syncLanes: SotSyncLane[]; reconciliation: SotReconciliation[]; flows: SotFlow[]; runbooks: SotRunbook[]; commands: SotCommand[]; risks: SotRisk[]; roadmap: Array<{ version: string; title: string; outcome: string; required: string[] }>; };
const readiness: ProductReadiness = {"websiteWebApp": 99, "taskProjectCore": 99, "backendApi": 99, "databasePrismaSeed": 99, "authRbac": 99, "iotOps": 92, "mobileApp": 90};
const metrics: SotMetric[] = [
  { id: "domains", label: "Source domains", value: "14", trend: "all modules mapped", status: "ready", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "adapters", label: "Adapters", value: "44", trend: "real, shadow, bridge, planned", status: "ready", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "contracts", label: "Data contracts", value: "42", trend: "canonical entity contracts", status: "ready", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "sync", label: "Sync lanes", value: "36", trend: "batch, realtime, audit and reconciliation", status: "shadow", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "reconcile", label: "Reconciliation checks", value: "30", trend: "blocking and warning parity rules", status: "guarded", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "commands", label: "Admin commands", value: "22", trend: "source control commands", status: "ready", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "runbooks", label: "Runbooks", value: "18", trend: "operational source runbooks", status: "ready", evidence: "visible in v5.0 source-of-truth dashboard" },
  { id: "risks", label: "Risk register", value: "22", trend: "source activation risks", status: "guarded", evidence: "visible in v5.0 source-of-truth dashboard" }
];
const domains: SotDomain[] = [
  { id: "tasks", label: "Taskuri", summary: "Task management source-of-truth", adapter: "Prisma Task Adapter", entity: "task", readiness: 99, mode: "env-gated", owner: "Platform Owner", endpoint: "/api/v1/work-os/domains/tasks/source-of-truth", writeMode: "env-gated", sourceSystem: "Prisma", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "projects", label: "Proiecte", summary: "Project portfolio source-of-truth", adapter: "Project Repository Adapter", entity: "project", readiness: 94, mode: "shadow", owner: "Operations Lead", endpoint: "/api/v1/work-os/domains/projects/source-of-truth", writeMode: "read-shadow", sourceSystem: "D1", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "stock", label: "Stocuri", summary: "Inventory and material movements source-of-truth", adapter: "Cloudflare D1 Stock Adapter", entity: "stock_item", readiness: 91, mode: "shadow", owner: "Database Owner", endpoint: "/api/v1/work-os/domains/stock/source-of-truth", writeMode: "read-shadow", sourceSystem: "Google Sheets", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "pontaj", label: "Pontaj", summary: "Timesheet, leave and workload capacity source-of-truth", adapter: "Apps Script + Sheets Bridge", entity: "time_event", readiness: 88, mode: "bridge-planned", owner: "Security/RBAC", endpoint: "/api/v1/work-os/domains/pontaj/source-of-truth", writeMode: "read-shadow", sourceSystem: "Audit Ledger", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "audit", label: "Audit", summary: "Evidence ledger source-of-truth", adapter: "Audit Ledger Adapter", entity: "audit_event", readiness: 99, mode: "ready", owner: "Warehouse Owner", endpoint: "/api/v1/work-os/domains/audit/source-of-truth", writeMode: "read-shadow", sourceSystem: "R2", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "adminControls", label: "Admin Controls", summary: "Command authority and incident source-of-truth", adapter: "Admin Command Adapter", entity: "admin_command", readiness: 99, mode: "ready", owner: "HR Ops", endpoint: "/api/v1/work-os/domains/adminControls/source-of-truth", writeMode: "read-shadow", sourceSystem: "Repository", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "users", label: "Users Directory", summary: "Employee, role and directory source-of-truth", adapter: "User Directory Adapter", entity: "user", readiness: 86, mode: "shadow", owner: "Field Ops", endpoint: "/api/v1/work-os/domains/users/source-of-truth", writeMode: "read-shadow", sourceSystem: "Prisma", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "documents", label: "Documente", summary: "Document evidence and attachment source-of-truth", adapter: "R2 Document Evidence Adapter", entity: "document", readiness: 84, mode: "shadow", owner: "Platform Owner", endpoint: "/api/v1/work-os/domains/documents/source-of-truth", writeMode: "read-shadow", sourceSystem: "D1", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "crm", label: "CRM Beneficiari", summary: "Client and beneficiary source-of-truth", adapter: "CRM Adapter", entity: "client", readiness: 78, mode: "planned", owner: "Operations Lead", endpoint: "/api/v1/work-os/domains/crm/source-of-truth", writeMode: "read-shadow", sourceSystem: "Google Sheets", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "offers", label: "Ofertare", summary: "Offers, BOM and reservation intent source-of-truth", adapter: "Offer Workspace Adapter", entity: "offer", readiness: 76, mode: "planned", owner: "Database Owner", endpoint: "/api/v1/work-os/domains/offers/source-of-truth", writeMode: "read-shadow", sourceSystem: "Audit Ledger", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "procurement", label: "Achizitii", summary: "Supplier requests and orders source-of-truth", adapter: "Procurement Adapter", entity: "purchase_request", readiness: 75, mode: "planned", owner: "Security/RBAC", endpoint: "/api/v1/work-os/domains/procurement/source-of-truth", writeMode: "read-shadow", sourceSystem: "R2", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "iotOps", label: "IoT Ops", summary: "PV/BESS/asset telemetry source-of-truth", adapter: "IoT Telemetry Adapter", entity: "telemetry_event", readiness: 82, mode: "shadow", owner: "Warehouse Owner", endpoint: "/api/v1/work-os/domains/iotOps/source-of-truth", writeMode: "read-shadow", sourceSystem: "Repository", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "reports", label: "Reports", summary: "Reporting snapshots and export source-of-truth", adapter: "Reporting Snapshot Adapter", entity: "report_snapshot", readiness: 80, mode: "shadow", owner: "HR Ops", endpoint: "/api/v1/work-os/domains/reports/source-of-truth", writeMode: "read-shadow", sourceSystem: "Prisma", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] },
  { id: "mobile", label: "Mobile Field App", summary: "Offline queue and field proposal source-of-truth", adapter: "Mobile Queue Adapter", entity: "mobile_event", readiness: 79, mode: "shadow", owner: "Field Ops", endpoint: "/api/v1/work-os/domains/mobile/source-of-truth", writeMode: "read-shadow", sourceSystem: "D1", targetSystem: "Work OS canonical read model", goLiveCriteria: ["adapter health green", "RBAC preflight present", "audit envelope present", "rollback snapshot valid"], blockers: ["production writes off by default", "requires source owner signoff"] }
];
const adapters: SotAdapter[] = [
  { id: "tasks-primary", label: "Taskuri Primary Adapter", domain: "tasks", kind: "Primary Adapter", mode: "env-gated", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/tasks-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/tasks-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "TASKS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "tasks-read-model", label: "Taskuri Read Model Adapter", domain: "tasks", kind: "Read Model Adapter", mode: "shadow", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/tasks-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/tasks-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "TASKS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "tasks-audit-tap", label: "Taskuri Audit Tap Adapter", domain: "tasks", kind: "Audit Tap Adapter", mode: "ready", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/tasks-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/tasks-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "TASKS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "projects-primary", label: "Proiecte Primary Adapter", domain: "projects", kind: "Primary Adapter", mode: "shadow", readiness: 94, endpoint: "/api/v1/enterprise/source-of-truth-adapters/projects-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/projects-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PROJECTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "projects-read-model", label: "Proiecte Read Model Adapter", domain: "projects", kind: "Read Model Adapter", mode: "shadow", readiness: 96, endpoint: "/api/v1/enterprise/source-of-truth-adapters/projects-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/projects-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PROJECTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "projects-audit-tap", label: "Proiecte Audit Tap Adapter", domain: "projects", kind: "Audit Tap Adapter", mode: "ready", readiness: 98, endpoint: "/api/v1/enterprise/source-of-truth-adapters/projects-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/projects-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PROJECTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "stock-primary", label: "Stocuri Primary Adapter", domain: "stock", kind: "Primary Adapter", mode: "shadow", readiness: 91, endpoint: "/api/v1/enterprise/source-of-truth-adapters/stock-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/stock-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "STOCK_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "stock-read-model", label: "Stocuri Read Model Adapter", domain: "stock", kind: "Read Model Adapter", mode: "shadow", readiness: 93, endpoint: "/api/v1/enterprise/source-of-truth-adapters/stock-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/stock-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "STOCK_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "stock-audit-tap", label: "Stocuri Audit Tap Adapter", domain: "stock", kind: "Audit Tap Adapter", mode: "ready", readiness: 95, endpoint: "/api/v1/enterprise/source-of-truth-adapters/stock-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/stock-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "STOCK_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "pontaj-primary", label: "Pontaj Primary Adapter", domain: "pontaj", kind: "Primary Adapter", mode: "bridge-planned", readiness: 88, endpoint: "/api/v1/enterprise/source-of-truth-adapters/pontaj-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/pontaj-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PONTAJ_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "pontaj-read-model", label: "Pontaj Read Model Adapter", domain: "pontaj", kind: "Read Model Adapter", mode: "shadow", readiness: 90, endpoint: "/api/v1/enterprise/source-of-truth-adapters/pontaj-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/pontaj-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PONTAJ_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "pontaj-audit-tap", label: "Pontaj Audit Tap Adapter", domain: "pontaj", kind: "Audit Tap Adapter", mode: "ready", readiness: 92, endpoint: "/api/v1/enterprise/source-of-truth-adapters/pontaj-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/pontaj-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PONTAJ_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "audit-primary", label: "Audit Primary Adapter", domain: "audit", kind: "Primary Adapter", mode: "ready", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/audit-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/audit-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "AUDIT_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "audit-read-model", label: "Audit Read Model Adapter", domain: "audit", kind: "Read Model Adapter", mode: "shadow", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/audit-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/audit-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "AUDIT_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "audit-audit-tap", label: "Audit Audit Tap Adapter", domain: "audit", kind: "Audit Tap Adapter", mode: "ready", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/audit-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/audit-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "AUDIT_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "adminControls-primary", label: "Admin Controls Primary Adapter", domain: "adminControls", kind: "Primary Adapter", mode: "ready", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/adminControls-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/adminControls-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "ADMINCONTROLS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "adminControls-read-model", label: "Admin Controls Read Model Adapter", domain: "adminControls", kind: "Read Model Adapter", mode: "shadow", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/adminControls-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/adminControls-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "ADMINCONTROLS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "adminControls-audit-tap", label: "Admin Controls Audit Tap Adapter", domain: "adminControls", kind: "Audit Tap Adapter", mode: "ready", readiness: 99, endpoint: "/api/v1/enterprise/source-of-truth-adapters/adminControls-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/adminControls-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "ADMINCONTROLS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "users-primary", label: "Users Directory Primary Adapter", domain: "users", kind: "Primary Adapter", mode: "shadow", readiness: 86, endpoint: "/api/v1/enterprise/source-of-truth-adapters/users-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/users-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "USERS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "users-read-model", label: "Users Directory Read Model Adapter", domain: "users", kind: "Read Model Adapter", mode: "shadow", readiness: 88, endpoint: "/api/v1/enterprise/source-of-truth-adapters/users-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/users-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "USERS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "users-audit-tap", label: "Users Directory Audit Tap Adapter", domain: "users", kind: "Audit Tap Adapter", mode: "ready", readiness: 90, endpoint: "/api/v1/enterprise/source-of-truth-adapters/users-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/users-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "USERS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "documents-primary", label: "Documente Primary Adapter", domain: "documents", kind: "Primary Adapter", mode: "shadow", readiness: 84, endpoint: "/api/v1/enterprise/source-of-truth-adapters/documents-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/documents-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "DOCUMENTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "documents-read-model", label: "Documente Read Model Adapter", domain: "documents", kind: "Read Model Adapter", mode: "shadow", readiness: 86, endpoint: "/api/v1/enterprise/source-of-truth-adapters/documents-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/documents-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "DOCUMENTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "documents-audit-tap", label: "Documente Audit Tap Adapter", domain: "documents", kind: "Audit Tap Adapter", mode: "shadow", readiness: 88, endpoint: "/api/v1/enterprise/source-of-truth-adapters/documents-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/documents-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "DOCUMENTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "crm-primary", label: "CRM Beneficiari Primary Adapter", domain: "crm", kind: "Primary Adapter", mode: "planned", readiness: 78, endpoint: "/api/v1/enterprise/source-of-truth-adapters/crm-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/crm-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "CRM_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "crm-read-model", label: "CRM Beneficiari Read Model Adapter", domain: "crm", kind: "Read Model Adapter", mode: "shadow", readiness: 80, endpoint: "/api/v1/enterprise/source-of-truth-adapters/crm-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/crm-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "CRM_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "crm-audit-tap", label: "CRM Beneficiari Audit Tap Adapter", domain: "crm", kind: "Audit Tap Adapter", mode: "shadow", readiness: 82, endpoint: "/api/v1/enterprise/source-of-truth-adapters/crm-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/crm-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "CRM_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "offers-primary", label: "Ofertare Primary Adapter", domain: "offers", kind: "Primary Adapter", mode: "planned", readiness: 76, endpoint: "/api/v1/enterprise/source-of-truth-adapters/offers-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/offers-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "OFFERS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "offers-read-model", label: "Ofertare Read Model Adapter", domain: "offers", kind: "Read Model Adapter", mode: "shadow", readiness: 78, endpoint: "/api/v1/enterprise/source-of-truth-adapters/offers-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/offers-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "OFFERS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "offers-audit-tap", label: "Ofertare Audit Tap Adapter", domain: "offers", kind: "Audit Tap Adapter", mode: "shadow", readiness: 80, endpoint: "/api/v1/enterprise/source-of-truth-adapters/offers-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/offers-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "OFFERS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "procurement-primary", label: "Achizitii Primary Adapter", domain: "procurement", kind: "Primary Adapter", mode: "planned", readiness: 75, endpoint: "/api/v1/enterprise/source-of-truth-adapters/procurement-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/procurement-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PROCUREMENT_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "procurement-read-model", label: "Achizitii Read Model Adapter", domain: "procurement", kind: "Read Model Adapter", mode: "shadow", readiness: 77, endpoint: "/api/v1/enterprise/source-of-truth-adapters/procurement-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/procurement-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PROCUREMENT_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "procurement-audit-tap", label: "Achizitii Audit Tap Adapter", domain: "procurement", kind: "Audit Tap Adapter", mode: "shadow", readiness: 79, endpoint: "/api/v1/enterprise/source-of-truth-adapters/procurement-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/procurement-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "PROCUREMENT_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "iotOps-primary", label: "IoT Ops Primary Adapter", domain: "iotOps", kind: "Primary Adapter", mode: "shadow", readiness: 82, endpoint: "/api/v1/enterprise/source-of-truth-adapters/iotOps-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/iotOps-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "IOTOPS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "iotOps-read-model", label: "IoT Ops Read Model Adapter", domain: "iotOps", kind: "Read Model Adapter", mode: "shadow", readiness: 84, endpoint: "/api/v1/enterprise/source-of-truth-adapters/iotOps-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/iotOps-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "IOTOPS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "iotOps-audit-tap", label: "IoT Ops Audit Tap Adapter", domain: "iotOps", kind: "Audit Tap Adapter", mode: "shadow", readiness: 86, endpoint: "/api/v1/enterprise/source-of-truth-adapters/iotOps-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/iotOps-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "IOTOPS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "reports-primary", label: "Reports Primary Adapter", domain: "reports", kind: "Primary Adapter", mode: "shadow", readiness: 80, endpoint: "/api/v1/enterprise/source-of-truth-adapters/reports-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/reports-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "REPORTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "reports-read-model", label: "Reports Read Model Adapter", domain: "reports", kind: "Read Model Adapter", mode: "shadow", readiness: 82, endpoint: "/api/v1/enterprise/source-of-truth-adapters/reports-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/reports-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "REPORTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "reports-audit-tap", label: "Reports Audit Tap Adapter", domain: "reports", kind: "Audit Tap Adapter", mode: "shadow", readiness: 84, endpoint: "/api/v1/enterprise/source-of-truth-adapters/reports-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/reports-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "REPORTS_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "mobile-primary", label: "Mobile Field App Primary Adapter", domain: "mobile", kind: "Primary Adapter", mode: "shadow", readiness: 79, endpoint: "/api/v1/enterprise/source-of-truth-adapters/mobile-primary", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/mobile-primary/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "MOBILE_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "mobile-read-model", label: "Mobile Field App Read Model Adapter", domain: "mobile", kind: "Read Model Adapter", mode: "shadow", readiness: 81, endpoint: "/api/v1/enterprise/source-of-truth-adapters/mobile-read-model", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/mobile-read-model/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "MOBILE_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" },
  { id: "mobile-audit-tap", label: "Mobile Field App Audit Tap Adapter", domain: "mobile", kind: "Audit Tap Adapter", mode: "shadow", readiness: 83, endpoint: "/api/v1/enterprise/source-of-truth-adapters/mobile-audit-tap", healthEndpoint: "/api/v1/enterprise/source-of-truth-adapters/mobile-audit-tap/health", requiredEnv: ["SOURCE_OF_TRUTH_MODE", "MOBILE_ADAPTER_MODE"], capabilities: ["read", "health", "snapshot", "audit", "rollback"], evidence: "adapter health + owner signoff + audit tap + rollback snapshot" }
];
const contracts: SotContract[] = [
  { id: "task.canonical.v1", entity: "task", domain: "tasks", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "task.snapshot.v1", entity: "task", domain: "tasks", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "task.mutation.v1", entity: "task", domain: "tasks", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "project.canonical.v1", entity: "project", domain: "projects", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 94, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "project.snapshot.v1", entity: "project", domain: "projects", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 94, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "project.mutation.v1", entity: "project", domain: "projects", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 94, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "stock_item.canonical.v1", entity: "stock_item", domain: "stock", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 91, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "stock_item.snapshot.v1", entity: "stock_item", domain: "stock", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 91, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "stock_item.mutation.v1", entity: "stock_item", domain: "stock", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 91, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "time_event.canonical.v1", entity: "time_event", domain: "pontaj", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 88, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "time_event.snapshot.v1", entity: "time_event", domain: "pontaj", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 88, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "time_event.mutation.v1", entity: "time_event", domain: "pontaj", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 88, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "audit_event.canonical.v1", entity: "audit_event", domain: "audit", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "audit_event.snapshot.v1", entity: "audit_event", domain: "audit", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "audit_event.mutation.v1", entity: "audit_event", domain: "audit", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "admin_command.canonical.v1", entity: "admin_command", domain: "adminControls", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "admin_command.snapshot.v1", entity: "admin_command", domain: "adminControls", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "admin_command.mutation.v1", entity: "admin_command", domain: "adminControls", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 99, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "user.canonical.v1", entity: "user", domain: "users", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 86, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "user.snapshot.v1", entity: "user", domain: "users", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 86, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "user.mutation.v1", entity: "user", domain: "users", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 86, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "document.canonical.v1", entity: "document", domain: "documents", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 84, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "document.snapshot.v1", entity: "document", domain: "documents", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 84, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "document.mutation.v1", entity: "document", domain: "documents", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 84, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "client.canonical.v1", entity: "client", domain: "crm", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 78, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "client.snapshot.v1", entity: "client", domain: "crm", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 78, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "client.mutation.v1", entity: "client", domain: "crm", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 78, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "offer.canonical.v1", entity: "offer", domain: "offers", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 76, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "offer.snapshot.v1", entity: "offer", domain: "offers", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 76, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "offer.mutation.v1", entity: "offer", domain: "offers", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 76, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "purchase_request.canonical.v1", entity: "purchase_request", domain: "procurement", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 75, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "purchase_request.snapshot.v1", entity: "purchase_request", domain: "procurement", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 75, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "purchase_request.mutation.v1", entity: "purchase_request", domain: "procurement", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 75, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "telemetry_event.canonical.v1", entity: "telemetry_event", domain: "iotOps", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 82, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "telemetry_event.snapshot.v1", entity: "telemetry_event", domain: "iotOps", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 82, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "telemetry_event.mutation.v1", entity: "telemetry_event", domain: "iotOps", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 82, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "report_snapshot.canonical.v1", entity: "report_snapshot", domain: "reports", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 80, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" },
  { id: "report_snapshot.snapshot.v1", entity: "report_snapshot", domain: "reports", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 80, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "R2" },
  { id: "report_snapshot.mutation.v1", entity: "report_snapshot", domain: "reports", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 80, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Google Sheets bridge" },
  { id: "mobile_event.canonical.v1", entity: "mobile_event", domain: "mobile", fields: ["id", "tenantId", "version", "updatedAt", "status", "ownerId"], purpose: "canonical source-of-truth contract", readiness: 79, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Audit Ledger" },
  { id: "mobile_event.snapshot.v1", entity: "mobile_event", domain: "mobile", fields: ["id", "snapshotAt", "source", "checksum", "payload"], purpose: "snapshot source-of-truth contract", readiness: 79, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "Prisma" },
  { id: "mobile_event.mutation.v1", entity: "mobile_event", domain: "mobile", fields: ["id", "actorId", "before", "after", "commandId", "rbacDecision"], purpose: "mutation source-of-truth contract", readiness: 79, version: "v1", auditRequired: true, rbacRequired: true, rollbackRequired: true, persistenceTarget: "D1" }
];
const syncLanes: SotSyncLane[] = [
  { id: "sync-tasks-read", label: "Taskuri read shadow sync", domain: "tasks", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 99, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-tasks-audit", label: "Taskuri audit envelope sync", domain: "tasks", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 99, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-projects-read", label: "Proiecte read shadow sync", domain: "projects", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 94, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-projects-audit", label: "Proiecte audit envelope sync", domain: "projects", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 97, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-stock-read", label: "Stocuri read shadow sync", domain: "stock", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 91, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-stock-audit", label: "Stocuri audit envelope sync", domain: "stock", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 94, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-pontaj-read", label: "Pontaj read shadow sync", domain: "pontaj", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 88, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-pontaj-audit", label: "Pontaj audit envelope sync", domain: "pontaj", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 91, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-audit-read", label: "Audit read shadow sync", domain: "audit", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 99, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-audit-audit", label: "Audit audit envelope sync", domain: "audit", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 99, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-adminControls-read", label: "Admin Controls read shadow sync", domain: "adminControls", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 99, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-adminControls-audit", label: "Admin Controls audit envelope sync", domain: "adminControls", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 99, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-users-read", label: "Users Directory read shadow sync", domain: "users", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 86, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-users-audit", label: "Users Directory audit envelope sync", domain: "users", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 89, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-documents-read", label: "Documente read shadow sync", domain: "documents", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 84, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-documents-audit", label: "Documente audit envelope sync", domain: "documents", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 87, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-crm-read", label: "CRM Beneficiari read shadow sync", domain: "crm", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 78, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-crm-audit", label: "CRM Beneficiari audit envelope sync", domain: "crm", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 81, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-offers-read", label: "Ofertare read shadow sync", domain: "offers", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 76, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-offers-audit", label: "Ofertare audit envelope sync", domain: "offers", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 79, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-procurement-read", label: "Achizitii read shadow sync", domain: "procurement", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 75, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-procurement-audit", label: "Achizitii audit envelope sync", domain: "procurement", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 78, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-iotOps-read", label: "IoT Ops read shadow sync", domain: "iotOps", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 82, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-iotOps-audit", label: "IoT Ops audit envelope sync", domain: "iotOps", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 85, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-reports-read", label: "Reports read shadow sync", domain: "reports", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 80, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-reports-audit", label: "Reports audit envelope sync", domain: "reports", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 83, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" },
  { id: "sync-mobile-read", label: "Mobile Field App read shadow sync", domain: "mobile", direction: "source -> Work OS read model", cadence: "15m", mode: "read-shadow", readiness: 79, guardrail: "no mutation without explicit env gate", audit: "checksum + actor + source version", rollback: "restore previous snapshot" },
  { id: "sync-mobile-audit", label: "Mobile Field App audit envelope sync", domain: "mobile", direction: "mutation -> audit ledger", cadence: "realtime", mode: "audit-required", readiness: 82, guardrail: "audit must be written before success", audit: "before/after + RBAC decision", rollback: "mark incident and replay last snapshot" }
];
const reconciliation: SotReconciliation[] = [
  { id: "reconcile-tasks-identity", label: "Taskuri identity parity", domain: "tasks", rule: "primary key + tenant + version parity", readiness: 99, severity: "blocking", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-projects-identity", label: "Proiecte identity parity", domain: "projects", rule: "primary key + tenant + version parity", readiness: 94, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-stock-identity", label: "Stocuri identity parity", domain: "stock", rule: "primary key + tenant + version parity", readiness: 91, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-pontaj-identity", label: "Pontaj identity parity", domain: "pontaj", rule: "primary key + tenant + version parity", readiness: 88, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-audit-identity", label: "Audit identity parity", domain: "audit", rule: "primary key + tenant + version parity", readiness: 99, severity: "blocking", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-adminControls-identity", label: "Admin Controls identity parity", domain: "adminControls", rule: "primary key + tenant + version parity", readiness: 99, severity: "blocking", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-users-identity", label: "Users Directory identity parity", domain: "users", rule: "primary key + tenant + version parity", readiness: 86, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-documents-identity", label: "Documente identity parity", domain: "documents", rule: "primary key + tenant + version parity", readiness: 84, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-crm-identity", label: "CRM Beneficiari identity parity", domain: "crm", rule: "primary key + tenant + version parity", readiness: 78, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-offers-identity", label: "Ofertare identity parity", domain: "offers", rule: "primary key + tenant + version parity", readiness: 76, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-procurement-identity", label: "Achizitii identity parity", domain: "procurement", rule: "primary key + tenant + version parity", readiness: 75, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-iotOps-identity", label: "IoT Ops identity parity", domain: "iotOps", rule: "primary key + tenant + version parity", readiness: 82, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-reports-identity", label: "Reports identity parity", domain: "reports", rule: "primary key + tenant + version parity", readiness: 80, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" },
  { id: "reconcile-mobile-identity", label: "Mobile Field App identity parity", domain: "mobile", rule: "primary key + tenant + version parity", readiness: 79, severity: "warning", action: "block promotion when failing", evidence: "nightly diff summary" }
];
const flows: SotFlow[] = [
  { id: "task-project", label: "Task -> Project", summary: "Task status updates project health", source: "tasks", target: "projects", status: "shadow", readiness: 86, contract: "task-project.contract.v1", adapter: "tasks-to-projects-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "project-stock", label: "Project -> Stock", summary: "Project phase creates stock reservation intent", source: "projects", target: "stock", status: "shadow", readiness: 87, contract: "project-stock.contract.v1", adapter: "projects-to-stock-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "stock-task", label: "Stock -> Task", summary: "Shortage creates task blocker", source: "stock", target: "tasks", status: "shadow", readiness: 88, contract: "stock-task.contract.v1", adapter: "stock-to-tasks-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "pontaj-task", label: "Pontaj -> Task", summary: "Capacity changes update workload", source: "pontaj", target: "tasks", status: "shadow", readiness: 89, contract: "pontaj-task.contract.v1", adapter: "pontaj-to-tasks-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "mobile-task", label: "Mobile -> Task", summary: "Field queue proposes task update", source: "mobile", target: "tasks", status: "shadow", readiness: 90, contract: "mobile-task.contract.v1", adapter: "mobile-to-tasks-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "audit-admin", label: "Audit -> Admin", summary: "Audit anomaly triggers command recommendation", source: "audit", target: "adminControls", status: "shadow", readiness: 91, contract: "audit-admin.contract.v1", adapter: "audit-to-adminControls-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "crm-project", label: "CRM -> Project", summary: "Accepted opportunity creates intake", source: "crm", target: "projects", status: "shadow", readiness: 92, contract: "crm-project.contract.v1", adapter: "crm-to-projects-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "offer-stock", label: "Offer -> Stock", summary: "BOM creates reservation intent", source: "offers", target: "stock", status: "shadow", readiness: 93, contract: "offer-stock.contract.v1", adapter: "offers-to-stock-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "procurement-stock", label: "Procurement -> Stock", summary: "Supplier order prepares stock intake", source: "procurement", target: "stock", status: "shadow", readiness: 94, contract: "procurement-stock.contract.v1", adapter: "procurement-to-stock-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "iot-task", label: "IoT -> Task", summary: "Telemetry alert creates operational task", source: "iotOps", target: "tasks", status: "shadow", readiness: 95, contract: "iot-task.contract.v1", adapter: "iotOps-to-tasks-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "document-audit", label: "Document -> Audit", summary: "Document anchors evidence ledger", source: "documents", target: "audit", status: "shadow", readiness: 96, contract: "document-audit.contract.v1", adapter: "documents-to-audit-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" },
  { id: "reports-executive", label: "Reports -> Management", summary: "Snapshots feed executive readiness", source: "reports", target: "audit", status: "shadow", readiness: 97, contract: "reports-executive.contract.v1", adapter: "reports-to-audit-bridge", audit: "before/after + owner + source version", rollback: "reverse bridge update and attach reconciliation diff" }
];
const runbooks: SotRunbook[] = [
  { id: "runbook-01", title: "Morning readiness", owner: "Operations Lead", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-02", title: "Adapter activation preflight", owner: "Database Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-03", title: "Nightly reconciliation", owner: "Security/RBAC", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-04", title: "Task write enable preflight", owner: "Warehouse Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-05", title: "Stock bridge verification", owner: "HR Ops", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-06", title: "Pontaj bridge sync review", owner: "Field Ops", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-07", title: "Audit event gap response", owner: "Platform Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-08", title: "Admin command approval", owner: "Operations Lead", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-09", title: "Mobile offline queue review", owner: "Database Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-10", title: "Source isolation incident", owner: "Security/RBAC", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-11", title: "Bridge rollback drill", owner: "Warehouse Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-12", title: "Entity contract migration", owner: "HR Ops", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-13", title: "Cross-module conflict resolution", owner: "Field Ops", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-14", title: "Executive readiness signoff", owner: "Platform Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-15", title: "Tenant data protection review", owner: "Operations Lead", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-16", title: "Weekly governance", owner: "Database Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-17", title: "Project-stock-pontaj review", owner: "Security/RBAC", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" },
  { id: "runbook-18", title: "Real adapter cutover ceremony", owner: "Warehouse Owner", steps: ["Open dashboard", "Check adapter health", "Verify reconciliation evidence", "Approve or keep read-only", "Record owner decision"], evidence: "signed note + health endpoint + audit snapshot" }
];
const commands: SotCommand[] = [
  { id: "cmd-01", title: "Enable read shadow", domain: "projects", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-01", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-02", title: "Disable read shadow", domain: "stock", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-02", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-03", title: "Freeze domain sync", domain: "pontaj", state: "locked", requiresApproval: true, command: "workos sot cmd-03", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-04", title: "Unfreeze domain sync", domain: "audit", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-04", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-05", title: "Isolate adapter", domain: "adminControls", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-05", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-06", title: "Restore adapter", domain: "users", state: "locked", requiresApproval: true, command: "workos sot cmd-06", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-07", title: "Force reconciliation", domain: "documents", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-07", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-08", title: "Drain mobile queue", domain: "crm", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-08", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-09", title: "Lock evidence bundle", domain: "offers", state: "locked", requiresApproval: true, command: "workos sot cmd-09", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-10", title: "Switch task writes canary", domain: "procurement", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-10", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-11", title: "Kill production writes", domain: "iotOps", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-11", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-12", title: "Set domain read-only", domain: "reports", state: "locked", requiresApproval: true, command: "workos sot cmd-12", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-13", title: "Rebuild read model", domain: "mobile", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-13", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-14", title: "Rollback mutation class", domain: "tasks", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-14", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-15", title: "Approve adapter cutover", domain: "projects", state: "locked", requiresApproval: true, command: "workos sot cmd-15", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-16", title: "Open incident bridge", domain: "stock", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-16", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-17", title: "Close incident bridge", domain: "pontaj", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-17", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-18", title: "Export audit bundle", domain: "audit", state: "locked", requiresApproval: true, command: "workos sot cmd-18", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-19", title: "Refresh source map", domain: "adminControls", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-19", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-20", title: "Reject adapter cutover", domain: "users", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-20", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-21", title: "Release read-only", domain: "documents", state: "locked", requiresApproval: true, command: "workos sot cmd-21", evidence: "admin actor + command id + affected domain + rollback plan" },
  { id: "cmd-22", title: "Run go/no-go", domain: "crm", state: "requires-approval", requiresApproval: true, command: "workos sot cmd-22", evidence: "admin actor + command id + affected domain + rollback plan" }
];
const risks: SotRisk[] = [
  { id: "risk-01", title: "Source conflict between UI and adapter", domain: "projects", severity: "medium", status: "controlled", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Operations Lead" },
  { id: "risk-02", title: "Pontaj bridge latency", domain: "stock", severity: "high", status: "monitoring", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Database Owner" },
  { id: "risk-03", title: "Stock reservation mismatch", domain: "pontaj", severity: "critical", status: "blocked", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Security/RBAC" },
  { id: "risk-04", title: "Audit envelope missing", domain: "audit", severity: "low", status: "open", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Warehouse Owner" },
  { id: "risk-05", title: "RBAC scope mismatch", domain: "adminControls", severity: "medium", status: "controlled", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "HR Ops" },
  { id: "risk-06", title: "Mobile duplicate event", domain: "users", severity: "high", status: "monitoring", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Field Ops" },
  { id: "risk-07", title: "Prisma/D1 parity mismatch", domain: "documents", severity: "critical", status: "blocked", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Platform Owner" },
  { id: "risk-08", title: "Project adapter stale milestone", domain: "crm", severity: "low", status: "open", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Operations Lead" },
  { id: "risk-09", title: "CRM duplicate client", domain: "offers", severity: "medium", status: "controlled", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Database Owner" },
  { id: "risk-10", title: "Offer BOM version drift", domain: "procurement", severity: "high", status: "monitoring", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Security/RBAC" },
  { id: "risk-11", title: "Procurement order mismatch", domain: "iotOps", severity: "critical", status: "blocked", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Warehouse Owner" },
  { id: "risk-12", title: "Document evidence orphan", domain: "reports", severity: "low", status: "open", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "HR Ops" },
  { id: "risk-13", title: "IoT false positive writes", domain: "mobile", severity: "medium", status: "controlled", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Field Ops" },
  { id: "risk-14", title: "Report stale export", domain: "tasks", severity: "high", status: "monitoring", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Platform Owner" },
  { id: "risk-15", title: "Tenant boundary leak", domain: "projects", severity: "critical", status: "blocked", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Operations Lead" },
  { id: "risk-16", title: "Admin command without evidence", domain: "stock", severity: "low", status: "open", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Database Owner" },
  { id: "risk-17", title: "Rollback snapshot expired", domain: "pontaj", severity: "medium", status: "controlled", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Security/RBAC" },
  { id: "risk-18", title: "Human approval bypass", domain: "audit", severity: "high", status: "monitoring", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Warehouse Owner" },
  { id: "risk-19", title: "Bridge connector outage", domain: "adminControls", severity: "critical", status: "blocked", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "HR Ops" },
  { id: "risk-20", title: "Schema contract incompatible", domain: "users", severity: "low", status: "open", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Field Ops" },
  { id: "risk-21", title: "Background sync storm", domain: "documents", severity: "medium", status: "controlled", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Platform Owner" },
  { id: "risk-22", title: "Queue dead letter growth", domain: "crm", severity: "high", status: "monitoring", mitigation: "adapter guardrails + reconciliation + audit evidence + owner signoff", owner: "Operations Lead" }
];
const roadmap: Release["roadmap"] = [
  { version: "5.1.0", title: "Production source cutover rehearsals", outcome: "Run cutover rehearsal for tasks, stock and pontaj sources", required: ["green adapters", "rollback drill", "tenant guard"] },
  { version: "5.2.0", title: "Global search and unified activity stream", outcome: "Expose source-of-truth events in unified Work OS activity", required: ["event contracts", "privacy filter", "index refresh"] },
  { version: "6.0.0", title: "Work OS GA operations console", outcome: "GA command console across all operational modules", required: ["go/no-go", "SLO dashboards", "incident drills"] }
];

export function getSourceOfTruthAdapterActivation(): Release { return { ok: true, version: "5.0.0", name: "Real Source-of-Truth Adapter Activation Pack", generatedAt: new Date().toISOString(), productionWrites: "off-by-default", summary: "Real source-of-truth adapter activation layer for Taskuri, Proiecte, Stocuri, Pontaj and Audit. This moves the platform from operations fabric into real adapters, source maps, reconciliation and domain cutover governance while keeping production writes off by default.", readiness, metrics, domains, adapters, contracts, syncLanes, reconciliation, flows, runbooks, commands, risks, roadmap }; }
export function getSourceOfTruthAdapterHealth() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), readiness, metrics, domains: domains.map((domain) => ({ id: domain.id, readiness: domain.readiness, mode: domain.mode, writeMode: domain.writeMode })), blockers: risks.filter((risk) => risk.severity === "critical" || risk.status === "blocked") }; }
export function getSourceOfTruthAdapterRegistry() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), adapters }; }
export function getSourceOfTruthContracts() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), contracts }; }
export function getSourceOfTruthSourceMap() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), domains: domains.map((domain) => ({ id: domain.id, label: domain.label, sourceSystem: domain.sourceSystem, targetSystem: domain.targetSystem, entity: domain.entity, adapter: domain.adapter })) }; }
export function getSourceOfTruthSyncPlan() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), syncLanes, flows }; }
export function getSourceOfTruthReconciliation() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), reconciliation }; }
export function getSourceOfTruthGovernance() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), commands, risks, runbooks }; }
export function getSourceOfTruthOperations() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), runbooks, commands, metrics }; }
export function getSourceOfTruthExecutiveReadiness() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), readiness, metrics, roadmap }; }
export function getSourceOfTruthDomainReadiness() { return { ok: true, version: "5.0.0", generatedAt: new Date().toISOString(), domains, adapters: adapters.map((adapter) => ({ id: adapter.id, domain: adapter.domain, readiness: adapter.readiness, mode: adapter.mode })) }; }
