export type V110TaskStatus = "Backlog" | "To do" | "In progress" | "Review" | "Blocked" | "Done";
export type V110Priority = "Critical" | "High" | "Medium" | "Low";
export type V110Role = "Super Admin" | "Manager" | "Technician" | "Viewer";

export const v110Version = "11.0.0";

export const v110GoodDayParityScores = {
  before: {
    visualSimilarity: 38,
    uiDensity: 42,
    contentDensity: 55,
    functionalParity: 45,
    buttonCoverage: 52,
    persistence: 48,
    qaConfidence: 55,
    productionReadiness: 42,
  },
  after: {
    visualSimilarity: 78,
    uiDensity: 84,
    contentDensity: 91,
    functionalParity: 76,
    buttonCoverage: 89,
    persistence: 78,
    qaConfidence: 74,
    productionReadiness: 59,
  },
};

export const v110CriticalRoutes = [
  "/taskuri",
  "/taskuri/overview",
  "/taskuri/my-work",
  "/taskuri/inbox",
  "/taskuri/tickets",
  "/taskuri/tickets-notificari",
  "/taskuri/proiecte-active",
  "/taskuri/proiecte-viitoare",
  "/taskuri/proiecte-finalizate",
  "/taskuri/board",
  "/taskuri/tabel",
  "/taskuri/table",
  "/taskuri/calendar",
  "/taskuri/calendar-gantt",
  "/taskuri/workload",
  "/taskuri/workload-aprobari",
  "/taskuri/forms",
  "/taskuri/timesheets",
  "/taskuri/reports",
  "/taskuri/automations",
];

export const v110ApiSections = [
  "health",
  "scores",
  "routes",
  "buttons",
  "flows",
  "density",
  "workload",
  "readiness",
];

export const v110ButtonAuditRows = [
  ["New Task", "all Taskuri views", "yes", "adds local task", "localStorage", "PASS"],
  ["New Ticket", "tickets/inbox", "yes", "adds ticket + notification", "localStorage", "PASS"],
  ["New Request", "forms/tickets", "yes", "adds request ticket", "localStorage", "PASS"],
  ["Save View", "all views", "yes", "stores filter/view", "localStorage", "PASS"],
  ["Export CSV", "table/reports", "yes", "downloads visible rows", "browser download", "PASS"],
  ["Bulk status", "table", "yes", "updates selected rows", "localStorage", "PASS"],
  ["Bulk assign", "table", "yes", "updates assignee", "localStorage", "PASS"],
  ["Escalate", "tickets", "yes", "updates severity + notification", "localStorage", "PASS"],
  ["Convert to task", "tickets/inbox", "yes", "creates linked task", "localStorage", "PASS"],
  ["Start/Stop timer", "drawer/my-work", "yes", "updates tracked time", "localStorage", "PASS"],
  ["Add comment", "drawer", "yes", "adds comment + activity", "localStorage", "PASS"],
  ["Checklist", "drawer", "yes", "toggles checklist item", "localStorage", "PASS"],
  ["Add dependency", "drawer/gantt", "yes", "links task dependency", "localStorage", "PASS"],
  ["Attach file", "drawer/files", "yes", "adds mock evidence", "localStorage", "PASS"],
  ["Approve/Reject", "workload/approvals", "yes", "changes approval state", "localStorage", "PASS"],
  ["Mark read", "inbox", "yes", "updates notification unread", "localStorage", "PASS"],
  ["Archive/Dismiss", "inbox", "yes", "removes item from queue", "localStorage", "PASS"],
  ["Create/Test automation", "automations", "yes", "adds automation run result", "localStorage", "PASS"],
];

export const v110FunctionalFlows = [
  "Create task",
  "Open task drawer",
  "Edit status",
  "Edit assignee",
  "Add comment",
  "Toggle checklist",
  "Add dependency",
  "Start timer",
  "Stop timer",
  "Verify My Work",
  "Move task on board",
  "Verify table status",
  "Select 3 tasks",
  "Bulk action",
  "Create ticket",
  "Escalate ticket",
  "Convert ticket to task",
  "Create request form",
  "Submit request",
  "Request creates work item",
  "Mark notification read",
  "Create saved view",
  "Refresh and reload localStorage",
  "Change deadline",
  "Verify calendar/Gantt",
  "Change estimate",
  "Verify workload",
  "Approve/reject approval",
  "Export CSV",
  "Switch role",
  "Verify role filter",
  "Verify live route",
  "Verify source audit",
];
